### ISSUE TITLE
How to create room and chat

### ISSUE THREAD

**Issue by Ashwinajackus** [nest-ionic-examples/02-chat-with-db#1]
I am able to create room I'd is created but while using name text nickname all are not storing 
Please help me out

**Comment by luisvt** [comment]
I upgraded nestjs and angular, please check again

**Comment by Ashwinajackus** [comment]
How to start socket server and test only in backend. Could you please help me on this

**Comment by luisvargasexepron** [comment]
First change to the api directory

```
cd chat-api
```

Then start the database

```
npm run dc:up:mongo
```

Then start the server api

```
npm run start
```

**Comment by luisvt** [comment]
First change to the api directory

```
cd chat-api
```

Then start the database

```
npm run dc:up:mongo
```

Then start the server api

```
npm run start
```
